replicaCount: 1

image:
  repository: ghcr.io/actions/gha-runner-scale-set-controller
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
