apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maxmind-license
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: maxmind-license
  data:
    - secretKey: license-key
      remoteRef:
        key: maxmind-credentials
        property: license-key
    - secretKey: account-id
      remoteRef:
        key: maxmind-credentials
        property: account-id
