apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: awx-postgres-configuration
  namespace: awx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: awx-postgres-configuration
    template:
      data:
        host: "postgresql.postgresql.svc.cluster.local"
        port: "5432"
        database: "awx"
        username: "postgres"
        password: "{{ .password }}"
        sslmode: "prefer"
        type: "unmanaged"
  data:
    - secretKey: password
      remoteRef:
        key: postgres-admin
        property: password
