apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepasswordSDK:
      vault: homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-credentials
          namespace: external-secrets
          key: token
