apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-admin
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: postgresql-admin
    template:
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: postgres-admin
        property: password
