apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres-password
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: n8n-postgres-password
    template:
      data:
        DB_POSTGRESDB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: postgres-admin
        property: password
