apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: medium-api-key
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: medium-api-key
    template:
      data:
        api-key: "{{ .apikey }}"
  data:
    - secretKey: apikey
      remoteRef:
        key: medium-api/api-key
