apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-password
  namespace: valkey
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: valkey-password
    template:
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: valkey
        property: password
