apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-wildcard-tls
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: homelab-wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.homelab.n2solutions.io"
    - homelab.n2solutions.io
