apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    template:
      data:
        api-token: "{{ .apitoken }}"
  data:
    - secretKey: apitoken
      remoteRef:
        key: cloudflare-dns
        property: api-token
