apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://ansible-community.github.io/awx-operator-helm/
      targetRevision: 3.2.1
      chart: awx-operator
      helm:
        valueFiles:
          - $values/manifests/awx/values.yaml
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      path: manifests/awx/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
        - .spec.target.template.engineVersion
        - .spec.target.template.mergePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
