apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-set
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.10.1
      helm:
        valueFiles:
          - $values/manifests/gha-runner/runner-set-values.yaml
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      path: manifests/gha-runner/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
        - .spec.target.template.engineVersion
        - .spec.target.template.mergePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
