apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: kagent/helm/kagent
      repoURL: ghcr.io/kagent-dev
      targetRevision: 0.7.23
      helm:
        valueFiles:
          - $values/manifests/kagent/values.yaml
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      path: manifests/kagent/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
        - .spec.target.template.engineVersion
        - .spec.target.template.mergePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
