apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 18.5.2
      helm:
        valueFiles:
          - $values/manifests/postgresql/values.yaml
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/n2solutionsio/homelab-gitops.git
      targetRevision: main
      path: manifests/postgresql/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
        - .spec.target.template.engineVersion
        - .spec.target.template.mergePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
