apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: op-sa-token
  namespace: arc-runners
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: op-sa-token
  data:
    - secretKey: OP_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: Service Account Auth Token: k3s-eso/credential
