apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-runner
  namespace: arc-runners
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: github-app-runner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: github-app-runner/app-id
    - secretKey: github_app_installation_id
      remoteRef:
        key: github-app-runner/installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: github-app-runner/private-key
