apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-pg-aiorg
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: grafana-pg-aiorg
    template:
      data:
        PG_AIORG_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: grafana-readonly-aiorg
        property: password
